# Generated by Django 4.1.1 on 2022-09-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="custom",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customers",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.drivers",
            ),
        ),
    ]
